Implemented new logic for I/O slots
ibm-openbmc/webui-vue pull request #138
Opened 2023-08-22 15:36 UTC by Nikhil-Ashoka

- Previously, we were comparing the slot's location number with the downstream adapter's location number and then pushing them to the I/O Slots list, Now we are comparing upstream fabric adapter with downstream adapter and pushing them to the list.

- Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=481314

2023-08-22 15:39 UTC, gtmills commented
Should we pull into 1040 as well? 
Does this work on Mex and Splitter?

2023-08-22 15:40 UTC, gtmills approved these changes
Seems reasonable, but would like to see this tested on mex and splitter

2023-08-22 21:31 UTC, baemyung commented
@Nikhil-Ashoka 

We're thinking to move this `UpstreamFabricAdapter` field from `Slot | Oem | IBM | UpstreamFabricAdapter' to `Slot | **Links** | Oem | IBM | UpstreamFabricAdapter`.

Is it causing too much on GUI side?
If not, I can make the change soon.

2023-08-22 21:35 UTC, gtmills requested changes
I think this is changing, sorry Nikhil

2023-08-22 22:40 UTC, baemyung commented
@Nikhil-Ashoka 
I've changed bmcweb - https://github.com/ibm-openbmc/bmcweb/pull/750
Please use it for your update and test.

Thanks

2023-08-23 13:45 UTC, gtmills approved these changes

2023-08-24 12:35 UTC, baemyung approved these changes

2023-08-25 02:53 UTC, Renuka9527 approved these changes

2023-09-07 18:39 UTC, merged