Added Dynamic Drawer
ibm-openbmc/webui-vue pull request #181
Opened 2024-02-06 06:13 UTC by SteffiAntony

Enabled TCE Table Pre-Allocation for Dynamic Drawer Add 
GUI JIRA: https://jsw.ibm.com/browse/PFEBMC-1500

2024-02-06 06:31 UTC, Renuka9527 commented on src/store/modules/ResourceManagement/ResourceMemoryStore.js
> +          console.log('error', error);
Just Add console.log(error) here

2024-02-06 06:33 UTC, Renuka9527 requested changes
Attach the screenshots and change the header to  Enablement TCE Table Pre-Allocation for Dynamic Drawer Add

2024-02-06 08:44 UTC, SteffiAntony commented
> Attach the screenshots and change the header to Enablement TCE Table Pre-Allocation for Dynamic Drawer Add

Screen shot for Everest and Rainer
<img width="1711" alt="Screenshot 2024-02-06 at 11 22 39 AM" src="https://github.com/ibm-openbmc/webui-vue/assets/125690789/cf0465eb-57e6-4d78-a5de-8e0e7d48ec3d">

Screen shot for Bonnell
<img width="1723" alt="Screenshot 2024-02-06 at 11 29 31 AM" src="https://github.com/ibm-openbmc/webui-vue/assets/125690789/95ef3d5d-bbea-4d44-87af-684d76db09d8">

2024-02-07 06:26 UTC, Renuka9527 approved these changes

2024-02-07 06:38 UTC, vedangimittal approved these changes

2024-02-07 06:53 UTC, nabilpandiyalayil approved these changes

2024-02-07 09:01 UTC, Nikhil-Ashoka commented on src/locales/en-US.json
> +    "dynamicIoDrawerAttachmentTitle":"Dynamic I/O Drawer Attachment",
Rename as "Dynamic I/O drawer attachment" to be consistent with the rest of the content in the page.

2024-02-07 09:03 UTC, Nikhil-Ashoka commented on src/locales/en-US.json
> +    "updateDynamicIoDrawerAttachment": "Update Dynamic I/O Drawer Attachment",
Rename as "Update dynamic I/O drawer attachment".

2024-02-07 09:04 UTC, Nikhil-Ashoka commented on src/locales/en-US.json
> +      "successSavingAdapterDynamicCapacity": "Successfully updated I/O adapter Drawer Attachment",
Rename as "Successfully updated I/O adapter drawer attachment"

2024-02-07 09:05 UTC, Nikhil-Ashoka commented on src/locales/en-US.json
> +      "errorSavingAdapterDynamicCapacity": "Error updating I/O adapter Drawer Attachment"
Rename as "Error updating I/O adapter drawer attachment"

2024-02-08 06:53 UTC, Nikhil-Ashoka approved these changes

2024-02-08 14:41 UTC, merged