Reverted “Service Login Certificate” updated using translation file from store
ibm-openbmc/webui-vue pull request #184
Opened 2024-02-09 11:32 UTC by Renuka9527

Description:
Reverted “Service Login Certificate” updated using translation file from store and added it in the vue with 'ServiceLogin Certificate' check and updating from translation file.

Defect:

2024-02-09 11:50 UTC, SteffiAntony approved these changes

2024-02-09 11:53 UTC, vedangimittal approved these changes

2024-02-14 09:26 UTC, Nikhil-Ashoka commented
@Renuka9527, The en-US.json file is not updated. Please pull the code.

2024-02-14 09:28 UTC, Nikhil-Ashoka requested changes
Pull to the latest code and push the changes. It is showing as blank.

2024-02-14 09:50 UTC, Nikhil-Ashoka approved these changes

2024-02-14 14:36 UTC, merged