Frequency cap value validation
ibm-openbmc/webui-vue pull request #188
Opened 2024-02-19 13:31 UTC by vedangimittal

- Error displayed on entering the invalid frequency cap value.
- Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=596253

2024-02-22 04:35 UTC, SteffiAntony approved these changes

2024-02-28 05:57 UTC, SteffiAntony approved these changes

2024-02-28 08:00 UTC, Renuka9527 commented
Please Add Screenshot

2024-02-28 09:04 UTC, vedangimittal commented
Before
<img width="1726" alt="Screenshot 2024-02-28 at 2 33 03 PM" src="https://github.com/ibm-openbmc/webui-vue/assets/69679625/6c1ed7ff-dbb3-426b-98d4-0a1ccbab8e7d">

After
<img width="1712" alt="Screenshot 2024-02-28 at 2 31 54 PM" src="https://github.com/ibm-openbmc/webui-vue/assets/69679625/a2af5a01-5795-4121-8a24-fbe90674126b">

2024-03-01 07:01 UTC, Nikhil-Ashoka requested changes
enter only alphabets or combination of letters and alphabets, It is accepting and submitted. Please re-check

2024-03-05 08:34 UTC, nabilpandiyalayil approved these changes

2024-03-05 14:01 UTC, Renuka9527 approved these changes

2024-03-06 17:42 UTC, merged