Removed Challenge Password option from Generate CSR panel
ibm-openbmc/webui-vue pull request #216
Opened 2024-04-08 11:13 UTC by vedangimittal

- Removed Challenge Password option from Generate CSR (under Certificates) panel
- Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=587393

2024-04-16 09:19 UTC, nabilpandiyalayil requested changes
Please fix these alignments....

![Screenshot 2024-04-16 at 11 09 35 AM](https://github.com/ibm-openbmc/webui-vue/assets/29519067/bfbc0b16-997e-4bd3-bd03-5a1040106697)

2024-04-18 11:19 UTC, nabilpandiyalayil approved these changes

2024-04-18 15:26 UTC, SteffiAntony approved these changes

2024-04-19 05:03 UTC, Renuka9527 approved these changes

2024-04-23 15:54 UTC, merged