Support for Concurrent maintenance in IPS Everest
ibm-openbmc/webui-vue pull request #227
Opened 2024-04-30 06:19 UTC by SteffiAntony

Modified the condition check for displaying the IPS equivalent Everest model along with Everest Concurrent Maintenance page, if it is an Everest model. 
Jira: https://jsw.ibm.com/browse/PFEBMC-2685
Signed-off-by: Steffi Antony <“steffiantony196@gmail.com”>

2024-04-30 10:12 UTC, Renuka9527 approved these changes

2024-05-03 13:36 UTC, Nikhil-Ashoka commented
@SteffiAntony, We need a defect and must-fix approval to get this merged.

2024-05-03 14:05 UTC, Nikhil-Ashoka requested changes
This || will not work.
you should use: 
`if (this.systemInfo?.startWith('9043') || this.systemInfo?.startWith('8860'))`

2024-05-07 09:54 UTC, Nikhil-Ashoka commented on src/env/components/AppNavigation/ibm.js
> +        this.systemInfo?.startWith('9043') ||
This should be startsWith, After making change, please test with an everest machine to see if it is working as expected

2024-05-07 09:54 UTC, Nikhil-Ashoka requested changes
Change startWith to startsWith

2024-05-07 10:35 UTC, SteffiAntony commented on src/env/components/AppNavigation/ibm.js
> +        this.systemInfo?.startWith('9043') ||
Resolved

2024-05-07 12:52 UTC, nabilpandiyalayil approved these changes

2024-05-07 13:16 UTC, Nikhil-Ashoka approved these changes

2024-05-07 22:04 UTC, merged