Informational message displayed to the user only when some power oper…
ibm-openbmc/webui-vue pull request #230
Opened 2024-05-03 09:16 UTC by vedangimittal

Informational message displayed to the user only when some power operation is confirmed by the user

- Informational message displayed to the user only when some power operation is confirmed by the user
- Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=613776

2024-05-03 14:07 UTC, Nikhil-Ashoka requested changes

2024-05-03 14:07 UTC, Nikhil-Ashoka commented on src/views/Operations/ServerPowerOperations/ServerPowerOperations.vue
> +              if (confirmed)
After if (confirmed), use {} to add the contents within it.

2024-05-07 06:19 UTC, nabilpandiyalayil commented on src/views/Operations/ServerPowerOperations/ServerPowerOperations.vue
> +                    this.$t('pageServerPowerOperations.userRefresh')
Use ';' instead of a comma operator for these expressions.

2024-05-07 14:15 UTC, Nikhil-Ashoka commented
Keep the Heading short

2024-05-08 13:07 UTC, Renuka9527 approved these changes

2024-05-08 13:15 UTC, nabilpandiyalayil approved these changes

2024-05-08 13:36 UTC, SteffiAntony approved these changes

2024-05-08 14:48 UTC, merged