Reduced API calls on System Parameters page
ibm-openbmc/webui-vue pull request #247
Opened 2024-06-20 08:54 UTC by vedangimittal

- Reduced API calls on System Parameters page for performance improvement
- Jira Story- https://jsw.ibm.com/browse/PFEBMC-2945

2024-06-28 07:06 UTC, vedangimittal commented
Will remove the comments before getting it merged.

2024-07-11 09:14 UTC, Nikhil-Ashoka commented on src/store/modules/ResourceManagement/SystemParametersStore.js
> +    async getApi({ commit }) {
Rename: "getApi" to "getBiosAttributesRegistry"

2024-07-11 09:15 UTC, Nikhil-Ashoka commented on src/views/ResourceManagement/SystemParameters/SystemParameters.vue
>      Promise.all([
No need of Promise.all as we are making only one API call

2024-07-11 09:15 UTC, Nikhil-Ashoka commented on src/store/modules/ResourceManagement/SystemParametersStore.js
> +    // async getAggressivePrefetch({ commit }) {
Remove unused code

2024-07-11 09:15 UTC, Nikhil-Ashoka commented on src/views/ResourceManagement/SystemParameters/SystemParameters.vue
> +      // this.$store.dispatch('systemParameters/getLateralCastOutMode'),
Remove unused code

2024-07-11 09:16 UTC, Nikhil-Ashoka requested changes
Please address the comments

2024-07-11 09:26 UTC, Nikhil-Ashoka commented on src/store/modules/ResourceManagement/SystemParametersStore.js
> -    async getRpdScheduledRun({ commit }) {
There is an error. The methods that you have removed, But being called somewhere in the code.

2024-07-11 09:28 UTC, Nikhil-Ashoka commented on src/store/modules/ResourceManagement/SystemParametersStore.js
> -    async getRpdScheduledRun({ commit }) {
Make sure that the method name that is removed is not being used anywhere in the code. Eg: Click on "Update RPD policy" and there is vuex error in console.
![image](https://github.com/ibm-openbmc/webui-vue/assets/96164786/e1486c96-b1dd-4e45-a6c2-6fa2e56a837a)

2024-07-12 09:41 UTC, nabilpandiyalayil commented on src/store/modules/ResourceManagement/SystemParametersStore.js
> +    // },
Please remove these lines.

2024-07-15 13:26 UTC, Nikhil-Ashoka approved these changes

2024-07-15 13:39 UTC, merged