Added key clear, Alert and status Icon, page Title  implementation
ibm-openbmc/webui-vue pull request #254
Opened 2024-07-09 11:04 UTC by Renuka9527

Description: Added key clear,keyclear store, Alert and status Icon, page Title  implementation.
Screenshot:
<img width="942" alt="image" src="https://github.com/ibm-openbmc/webui-vue/assets/110152569/97566a69-843b-4cc6-8671-24120bfe32fe">
<img width="815" alt="image" src="https://github.com/ibm-openbmc/webui-vue/assets/110152569/384c37dc-8297-4a84-8f88-51f2689c0121">
<img width="952" alt="image" src="https://github.com/ibm-openbmc/webui-vue/assets/110152569/f58caddf-a3b1-49e0-914c-5d0603a2b100">

2024-07-16 16:00 UTC, Nikhil-Ashoka commented
I am getting a blank page, an error message in the console saying: "TypeError: useLoadingBarComposable is not a function
    at setup"

2024-07-16 16:13 UTC, Nikhil-Ashoka commented
Loading Bar is not present in Key Clear in Vue2 as well. So, we can remove it altogether.

2024-07-16 16:16 UTC, Nikhil-Ashoka requested changes
service user will have 2 more options in the page. Seems to be missing.

2024-07-17 07:52 UTC, Renuka9527 commented
> service user will have 2 more options in the page. Seems to be missing.

Addressed

2024-07-17 07:53 UTC, Renuka9527 commented
> @Renuka9527 I am getting a blank page, an error message in the console saying: "TypeError: useLoadingBarComposable is not a function at setup"

Removed loading bar

2024-07-18 07:35 UTC, nabilpandiyalayil requested changes

2024-07-18 07:35 UTC, nabilpandiyalayil commented on src/views/Operations/KeyClear/KeyClear.vue
> +      console.log(message);
Please remove the console logs.

2024-07-18 07:35 UTC, nabilpandiyalayil commented on src/views/Operations/KeyClear/KeyClear.vue
> +      console.log(message);
Here also

2024-07-18 07:35 UTC, nabilpandiyalayil commented on src/views/Operations/KeyClear/KeyClear.vue
> +import useToast from '../../../components/Composables/useToastComposable';
Try to import the components using '@' instead.

2024-07-18 08:02 UTC, nabilpandiyalayil requested changes

2024-07-18 08:02 UTC, nabilpandiyalayil commented on src/views/Operations/KeyClear/KeyClear.vue
> +      successToast(t('pageKeyClear.toast.selectedKeyClearedSuccess'));
Use the returned message value in here instead of 'pageKeyClear.toast.selectedKeyClearedSuccess'. Don't **deconstruct** the message from the above then statement.

2024-07-18 08:02 UTC, nabilpandiyalayil commented on src/views/Operations/KeyClear/KeyClear.vue
> +      errorToast(t('pageKeyClear.toast.selectedKeyClearedError'));
Here also, use the message variable.

2024-07-19 07:01 UTC, Renuka9527 commented on src/views/Operations/KeyClear/KeyClear.vue
> +      successToast(t('pageKeyClear.toast.selectedKeyClearedSuccess'));
Adressed as discussed offline

2024-07-19 07:01 UTC, Renuka9527 commented on src/views/Operations/KeyClear/KeyClear.vue
> +      errorToast(t('pageKeyClear.toast.selectedKeyClearedError'));
Same as mentioned above

2024-07-19 07:32 UTC, Renuka9527 commented
> service user will have 2 more options in the page. Seems to be missing.

Addressed

2024-07-19 07:32 UTC, Renuka9527 commented on src/views/Operations/KeyClear/KeyClear.vue
> +import useToast from '../../../components/Composables/useToastComposable';
Addressed

2024-07-19 07:32 UTC, Renuka9527 commented on src/views/Operations/KeyClear/KeyClear.vue
> +      console.log(message);
Addressed

2024-07-19 07:32 UTC, Renuka9527 commented on src/views/Operations/KeyClear/KeyClear.vue
> +      console.log(message);
Addressed

2024-07-19 08:27 UTC, nabilpandiyalayil approved these changes

2024-07-22 05:55 UTC, Nikhil-Ashoka approved these changes

2024-07-22 15:36 UTC, merged