Testing Purpose - Pinia composition api implementation
ibm-openbmc/webui-vue pull request #262
Opened 2024-07-24 08:50 UTC by SteffiAntony

Files changed:
    src/router/routes.js
    src/store/modules/SecurityAndAccess/PoliciesStore.js
    src/store/modules/SecurityAndAccess/UserManagementStore.js
    src/views/SecurityAndAccess/Policies/Policies.vue
    src/App.vue
    src/assets/styles/bmc/custom/_forms.scss
    src/components/Global/StatusIcon.vue
    src/components/Composables/useToastComposable.js

Signed-off-by: Steffi Antony <“steffiantony196@gmail.com”>

2024-08-01 06:50 UTC, nabilpandiyalayil requested changes

2024-08-01 06:50 UTC, nabilpandiyalayil commented on src/views/SecurityAndAccess/Policies/Policies.vue
> -        <b-row v-if="isAdminUser || isServiceUser" class="section-divider">
This condition is required

2024-08-01 06:50 UTC, nabilpandiyalayil commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +                <span v-b-tooltip="$t('global.status.nextReboot')">
Try to use InfoTooltip global component here

2024-08-01 06:50 UTC, nabilpandiyalayil commented on src/views/SecurityAndAccess/Policies/Policies.vue
> -              :disabled="!(isAdminUser || isServiceUser)"
This condition is required.

2024-08-01 06:50 UTC, nabilpandiyalayil commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +  <div class="container" fluid="xl">
Use BContainer

2024-08-05 06:58 UTC, Nikhil-Ashoka commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +                  <status-icon status="time" />
Icon is bigger. Make it 16*16px. It is currently 20*20px

2024-08-05 07:00 UTC, Nikhil-Ashoka commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +      title="Unauthenticated ACF upload enablement"
Use from translation file

2024-08-05 07:00 UTC, Nikhil-Ashoka commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +      ok-title="confirm"
"cancel" and "confirm" take from the translation file

2024-08-05 07:01 UTC, Nikhil-Ashoka commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +      @ok="onModalOk"
Size of cancel and confirm buttons are different.

2024-08-05 07:02 UTC, Nikhil-Ashoka commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +    <BModal
Try to implement in composables here. will be required for upcoming implementations.

2024-08-07 05:34 UTC, nabilpandiyalayil commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +                  <status-icon status="time" />
I think including time as a status icon is a bit confusing. Can we use the icon-time component in here like it was before? StatusIcon component should only have  icons representing status.

2024-08-07 05:34 UTC, nabilpandiyalayil commented on src/components/Global/StatusIcon.vue
> +import IconTime from '@carbon/icons-vue/es/time/20';
I'm not comfortable with this change. This is not technically a status icon.

2024-08-09 10:28 UTC, nabilpandiyalayil requested changes

2024-08-09 10:28 UTC, nabilpandiyalayil commented on src/components/Global/StatusIcon.vue
> +import IconTime from '@carbon/icons-vue/es/time/20';
This is no longer required. Please remove.

2024-08-09 10:28 UTC, nabilpandiyalayil commented on src/components/Global/StatusIcon.vue
> +  }
This one also.

2024-08-12 06:57 UTC, nabilpandiyalayil requested changes

2024-08-12 06:57 UTC, nabilpandiyalayil commented on src/views/SecurityAndAccess/Policies/Policies.vue
> +      ok-title="confirm"
Use from the translation file.

2024-08-12 07:19 UTC, nabilpandiyalayil approved these changes

2024-08-12 10:34 UTC, Nikhil-Ashoka approved these changes

2024-08-12 15:47 UTC, merged