Implement power policy page.
ibm-openbmc/webui-vue pull request #265
Opened 2024-07-31 14:51 UTC by SteffiAntony

Implemented power policy page
Jira: https://jsw.ibm.com/browse/PFEBMC-2404

2024-08-01 05:51 UTC, nabilpandiyalayil requested changes

2024-08-01 05:51 UTC, nabilpandiyalayil commented on src/views/Settings/PowerRestorePolicy/PowerRestorePolicy.vue
> +  <div class="container" fluid="xl">
Use BContainer

2024-08-01 05:51 UTC, nabilpandiyalayil commented on src/views/Settings/PowerRestorePolicy/PowerRestorePolicy.vue
> +import BootSettingsStore from '../../../store/modules/Operations/BootSettingsStore';
Import using '@'

2024-08-17 07:03 UTC, Nikhil-Ashoka requested changes

2024-08-17 07:03 UTC, Nikhil-Ashoka commented on src/views/Settings/PowerRestorePolicy/PowerRestorePolicy.vue
> +    <BButton
There is no gap between the options and the Save button. Please make this change

2024-08-21 09:00 UTC, nabilpandiyalayil requested changes

2024-08-21 09:00 UTC, nabilpandiyalayil commented on src/views/Settings/PowerRestorePolicy/PowerRestorePolicy.vue
> +import BootSettingsStore from '@/store/modules/Operations/BootSettingsStore';
Import from '@/store'

2024-08-21 15:59 UTC, Nikhil-Ashoka approved these changes

2024-08-23 14:52 UTC, Nikhil-Ashoka approved these changes

2024-08-27 10:08 UTC, nabilpandiyalayil approved these changes

2024-08-27 13:49 UTC, merged