Removed display of information message when readonly user is logged in
ibm-openbmc/webui-vue pull request #268
Opened 2024-08-05 10:01 UTC by vedangimittal

- Removed display of information message when readonly user is logged in
- Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=635517

2024-08-12 15:04 UTC, Nikhil-Ashoka commented
Keep the heading short

2024-08-22 04:46 UTC, SteffiAntony approved these changes

2024-08-22 05:51 UTC, Nikhil-Ashoka requested changes
Not convinced with this change. It will only cover the read-only user, If the operation fails for some reason, we would still get this info message. Need a better way to solve the issue.

2024-08-22 05:52 UTC, Nikhil-Ashoka commented
<img width="1092" alt="Screenshot 2024-08-22 at 11 20 56 AM" src="https://github.com/user-attachments/assets/235f1e4c-7abb-4efb-8a2d-f6b4691c7020">
The API for shut down is failing, but the info toast to reload the browser is still displayed. We should only show this toast message when the API is giving success

2024-09-25 06:27 UTC, nabilpandiyalayil requested changes

2024-09-25 06:27 UTC, nabilpandiyalayil commented on src/store/modules/Operations/ControlStore.js
>        dispatch('getLastPowerOperationTime');
We won't be getting the toast immediately when login as service user. checkForServerStatus takes 5 mins to resolve. Better to offload line 92 to 94 to a new async function.

2024-10-16 05:59 UTC, nabilpandiyalayil requested changes

2024-10-16 05:59 UTC, nabilpandiyalayil commented on src/store/modules/Operations/ControlStore.js
> +      await checkForServerStatus.bind(arr)(value);
this should be `await checkForServerStatus.bind(arr, value)()`

2024-10-17 08:27 UTC, nabilpandiyalayil approved these changes

2024-10-17 12:59 UTC, Nikhil-Ashoka approved these changes

2024-10-17 14:16 UTC, merged