Fixed refetching of values for capacity on demand page  on new license activation.
ibm-openbmc/webui-vue pull request #270
Opened 2024-08-12 08:36 UTC by tiwari-nishant

•  Fixed refetching of values for capacity on demand page  on new license activation.
•  Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=638365

2024-08-12 15:03 UTC, Nikhil-Ashoka commented
Keep the heading short

2024-08-13 08:43 UTC, tiwari-nishant commented
done @Nikhil-Ashoka

2024-08-14 13:32 UTC, Nikhil-Ashoka requested changes
We can optimize the code here by calling **fetchInfo()** in the created method also.

2024-08-27 13:29 UTC, Nikhil-Ashoka approved these changes

2024-08-28 04:36 UTC, nabilpandiyalayil approved these changes

2024-08-28 09:07 UTC, vedangimittal approved these changes

2024-08-28 13:22 UTC, merged