•	Fixed conditional alert informational message when the system is hmc-managed 
ibm-openbmc/webui-vue pull request #271
Opened 2024-08-12 13:01 UTC by tiwari-nishant

·      Fixed conditional alert informational message when the system is hmc-managed 
·      Defect: https://jazz07.rchland.ibm.com:13443/jazz/web/projects/CSSD#action=com.ibm.team.workitem.viewWorkItem&id=638513

2024-08-12 15:02 UTC, Nikhil-Ashoka commented
Keep the Heading Short. Something like "Fixed alert message in Server power operations"

2024-08-13 08:42 UTC, tiwari-nishant commented
Done @Nikhil-Ashoka

2024-08-14 13:25 UTC, Nikhil-Ashoka commented
@tiwari-nishant, This condition is working as expected now. Although, we have another scenario. Once we click on continue to OS running, We will still get the message. There also, you need to add this HMC managed condition before displaying

2024-08-14 13:26 UTC, Nikhil-Ashoka requested changes

2024-08-14 13:26 UTC, Nikhil-Ashoka commented on src/views/Operations/ServerPowerOperations/BootSettings.vue
>                  this.infoToast(
This is the other place where the condition is required.

2024-08-27 13:32 UTC, Nikhil-Ashoka approved these changes

2024-08-28 04:27 UTC, nabilpandiyalayil approved these changes

2024-08-28 09:56 UTC, vedangimittal approved these changes

2024-08-28 13:21 UTC, merged