Implement Factory reset
ibm-openbmc/webui-vue pull request #274
Opened 2024-08-14 07:52 UTC by SteffiAntony

jira: https://jsw.ibm.com/browse/PFEBMC-2382

2024-08-21 08:55 UTC, nabilpandiyalayil requested changes

2024-08-21 08:55 UTC, nabilpandiyalayil commented on src/views/Operations/FactoryReset/FactoryResetModal.vue
> +    v-model="modal"
This is no longer required.

2024-08-21 08:55 UTC, nabilpandiyalayil commented on src/views/Operations/FactoryReset/FactoryReset.vue
> +import FactoryResetStore from '@/store/modules/Operations/FactoryResetStore';
Import these from '@/store'

2024-08-21 08:55 UTC, nabilpandiyalayil commented on src/views/Operations/FactoryReset/FactoryReset.vue
> +import { GlobalStore } from '@/store/modules/GlobalStore';
Just import from '@/store'

2024-08-21 08:55 UTC, nabilpandiyalayil commented on src/views/Operations/FactoryReset/FactoryReset.vue
> +import PageTitle from '../../../components/Global/PageTitle.vue';
Use '@' to import

2024-08-21 08:55 UTC, nabilpandiyalayil commented on src/views/Operations/FactoryReset/FactoryReset.vue
> +const emit = defineEmits(['loading-bar-status']);
Please explain the need for these emits

2024-08-21 14:14 UTC, SteffiAntony commented on src/views/Operations/FactoryReset/FactoryReset.vue
> +const emit = defineEmits(['loading-bar-status']);
Sorry. Just forgot to remove these lines

2024-08-23 14:59 UTC, Nikhil-Ashoka requested changes
The styling is not as it was in Factory Reset page in Vue2 code.
The text should be properly aligned as it is in vue2 and Button must have gap.

2024-08-23 15:04 UTC, Nikhil-Ashoka commented
![Uploading Screenshot 2024-08-23 at 8.31.03 PM.png…]()

2024-08-23 15:05 UTC, Nikhil-Ashoka commented
<img width="631" alt="Screenshot 2024-08-23 at 1 02 01 PM" src="https://github.com/user-attachments/assets/9bf0a930-313c-40c3-ba62-8d9b7b37e185">

2024-08-23 15:06 UTC, Nikhil-Ashoka commented
<img width="1726" alt="Screenshot 2024-08-23 at 8 31 03 PM" src="https://github.com/user-attachments/assets/5fb1f81f-dc4b-4254-b141-123863ab67b7">

2024-08-30 05:57 UTC, nabilpandiyalayil requested changes

2024-08-30 05:57 UTC, nabilpandiyalayil commented on src/store/modules/Operations/FactoryResetStore.js
> +            i18n.globalt('pageFactoryReset.toast.resetBiosError'),
fix the typo "globalt"

2024-08-30 05:57 UTC, nabilpandiyalayil commented on src/store/modules/Settings/PowerPolicyStore.js
why this file in this PR?

2024-08-30 05:57 UTC, nabilpandiyalayil commented on src/views/Settings/PowerRestorePolicy/PowerRestorePolicy.vue
Here also

2024-09-02 04:15 UTC, SteffiAntony commented on src/store/modules/Settings/PowerPolicyStore.js
By resolving a merge conflict after taking the lastest pull, this file was pushed

2024-09-02 04:16 UTC, SteffiAntony commented on src/views/Settings/PowerRestorePolicy/PowerRestorePolicy.vue
By resolving a merge conflict after taking the latest pull, this file was pushed.

2024-09-02 09:32 UTC, nabilpandiyalayil commented on src/router/routes.js
> +      },
This should not be added again. Please pull the latest changes.

2024-09-03 04:16 UTC, Nikhil-Ashoka requested changes

2024-09-03 04:16 UTC, Nikhil-Ashoka commented on src/views/Operations/FactoryReset/FactoryReset.vue
> +const Global = GlobalStore();
let the variable names start with lowercase: "globalStore", "authenticationStore", "factoryResetStore", "toast"

2024-09-03 10:49 UTC, Nikhil-Ashoka approved these changes

2024-09-03 12:44 UTC, nabilpandiyalayil approved these changes

2024-09-04 13:00 UTC, merged