Implemented Certificates and ModalUploadCertificate pages
ibm-openbmc/webui-vue pull request #281
Opened 2024-09-06 07:45 UTC by SteffiAntony

Jira: https://jsw.ibm.com/browse/PFEBMC-2392
Jira: https://jsw.ibm.com/browse/PFEBMC-2373

2024-09-25 06:59 UTC, nabilpandiyalayil requested changes

2024-09-25 06:59 UTC, nabilpandiyalayil commented on src/store/modules/SecurityAndAccess/CertificatesStore.js
> +      console.log('availableUploadType:', availableUploadType);
Remove console log

2024-09-25 06:59 UTC, nabilpandiyalayil commented on src/views/SecurityAndAccess/Certificates/Certificates.vue
> +            {{ value }}
use filters

2024-09-25 06:59 UTC, nabilpandiyalayil commented on src/views/SecurityAndAccess/Certificates/Certificates.vue
> +            {{ value }}
here also

2024-10-01 10:41 UTC, Nikhil-Ashoka commented on src/assets/styles/bmc/custom/_forms.scss
> +      inset 0 0 0 3px theme-color('primary'),
Theme-color is dropped in Bootstrap5

2024-10-05 15:19 UTC, Nikhil-Ashoka commented
New PR: https://github.com/ibm-openbmc/webui-vue/pull/295

2024-10-05 15:19 UTC, closed without merging