Implemented Sessions page
ibm-openbmc/webui-vue pull request #284
Opened 2024-09-10 10:33 UTC by vedangimittal

- Implemented Sessions page
- Jira story: https://jsw.ibm.com/browse/PFEBMC-2397

2024-09-19 08:34 UTC, vedangimittal commented
- Checkbox - row select functionality is still broken
- Changes required in TableRowAction.vue file

2024-10-04 06:35 UTC, Nikhil-Ashoka commented on src/locales/en-US.json
> +      "disconnectMessage": "Are you sure you want to disconnect 1 session? This action cannot be undone. | Are you sure you want to disconnect %{count} sessions? This action cannot be undone.",
@vedangimittal, This change is already present in other languages. So, I would prefer us using the same Message and avoid rework for this in translation files.
Eg: https://github.ibm.com/openbmc/webui-vue/blob/1060-ghe/src/locales/de.json

2024-10-04 06:37 UTC, Nikhil-Ashoka commented on src/views/SecurityAndAccess/Sessions/Sessions.vue
> +            <!-- @update:modelValue="toggleOne" -->
Remove unused code.

2024-10-04 06:46 UTC, Nikhil-Ashoka requested changes

2024-10-04 06:46 UTC, Nikhil-Ashoka commented on src/views/SecurityAndAccess/Sessions/Sessions.vue
> +    <BModal
Here, I think we can use only 1 modal and optimize?

2024-10-07 08:27 UTC, Nikhil-Ashoka requested changes

2024-10-07 08:27 UTC, Nikhil-Ashoka commented on src/views/SecurityAndAccess/Sessions/Sessions.vue
> +      <BCol sm="6" md="5" xl="4" class="searchStyle">
SearchStyle is not used. Hence, styling is not proper.
<img width="1674" alt="Screenshot 2024-10-07 at 1 54 45 PM" src="https://github.com/user-attachments/assets/533c18c1-bf63-465a-a329-bfa625bdd394">

2024-10-07 10:27 UTC, Nikhil-Ashoka approved these changes

2024-10-07 12:42 UTC, nabilpandiyalayil approved these changes

2024-10-07 13:27 UTC, merged