Implement Firmware page
ibm-openbmc/webui-vue pull request #297
Opened 2024-10-08 08:50 UTC by nabilpandiyalayil

- Navigation: Operations > Firmware

 - Before running, add the following env variables to .env.local file:
   - `VITE_APP_SERVER_OFF_REQUIRED=true`
   - `VITE_APP_TFTP_SERVER=false`

 - Jira: https://jsw.ibm.com/browse/PFEBMC-2389

2024-10-08 15:56 UTC, Nikhil-Ashoka requested changes

2024-10-08 15:56 UTC, Nikhil-Ashoka commented on src/views/Operations/Firmware/FirmwareAlertServerPower.vue
> +  isServerOff: {
Looks like the warning message is not being displayed when the system is Powered On

2024-10-08 15:56 UTC, Nikhil-Ashoka commented on src/views/Operations/Firmware/FirmwareFormUpdate.vue
>            :disabled="isPageDisabled"
The buttons are enabled when the system is powered On. Should be greyed out.

2024-10-09 04:30 UTC, nabilpandiyalayil commented on src/views/Operations/Firmware/FirmwareAlertServerPower.vue
> +  isServerOff: {
We need to add `VITE_APP_SERVER_OFF_REQUIRED=true` to env variable inorder to display.

2024-10-09 04:30 UTC, nabilpandiyalayil commented on src/views/Operations/Firmware/FirmwareFormUpdate.vue
>            :disabled="isPageDisabled"
Same comment as in above.

2024-10-09 06:24 UTC, Nikhil-Ashoka approved these changes

2024-10-09 13:26 UTC, merged