Prefix length fix
ibm-openbmc/webui-vue pull request #301
Opened 2024-10-23 09:09 UTC by tiwari-nishant

* Removed Prefix Length input field from IPV6DefaultGatewaytable
* Jira Story: https://jsw.ibm.com/browse/PFEBMC-3374

2024-11-06 10:59 UTC, nabilpandiyalayil commented on src/views/Settings/Network/ModalIpv6StaticDefaultGateway.vue
> +              style="width: 215%"
I prefer a separate style tag. This works but we don't use style attribute in our codebase.

2024-11-07 09:41 UTC, tiwari-nishant commented on src/views/Settings/Network/ModalIpv6StaticDefaultGateway.vue
> +              style="width: 215%"
Updated @nabilpandiyalayil

2024-11-12 08:09 UTC, Nikhil-Ashoka requested changes
Edit operation is failing for IPv6 static default gateways address.

2025-01-01 07:31 UTC, Nikhil-Ashoka requested changes

2025-01-01 07:31 UTC, Nikhil-Ashoka commented on src/views/Settings/Network/ModalIpv6StaticDefaultGateway.vue
> +<style scoped>
You don't need to make this styling change. In b-col, remove sm=6 and it should work as expected.

2025-01-06 07:46 UTC, tiwari-nishant commented on src/views/Settings/Network/ModalIpv6StaticDefaultGateway.vue
> +<style scoped>
Updated

2025-01-06 08:31 UTC, Nikhil-Ashoka approved these changes

2025-01-07 16:50 UTC, merged