Implemented System Parameters Page
ibm-openbmc/webui-vue pull request #310
Opened 2024-11-22 10:34 UTC by vedangimittal

- Implemented System Parameters Page - 1060
- Jira Story: https://jsw.ibm.com/browse/PFEBMC-2390

2024-12-02 17:38 UTC, Nikhil-Ashoka requested changes
Getting success when we have empty values in "RPD scheduled run time of day". It should throw error

2024-12-03 04:40 UTC, nabilpandiyalayil requested changes

2024-12-03 04:40 UTC, nabilpandiyalayil commented on src/views/ResourceManagement/SystemParameters/RuntimeProcessorDiagnostic.vue
> +  console.log('systemParametersStore.rpdFeatureOptionsGetter', systemParametersStore.rpdFeatureOptionsGetter);
Remove console log

2024-12-03 04:40 UTC, nabilpandiyalayil commented on src/views/ResourceManagement/SystemParameters/RuntimeProcessorDiagnostic.vue
> +// });
I think these watchers should be enabled.

2024-12-03 06:31 UTC, vedangimittal commented on src/views/ResourceManagement/SystemParameters/RuntimeProcessorDiagnostic.vue
> +// });
selectedItem and selectedFeatureItem do not exist in any file

2024-12-04 15:51 UTC, Nikhil-Ashoka approved these changes

2024-12-05 05:48 UTC, nabilpandiyalayil approved these changes

2024-12-05 14:27 UTC, merged