Implemented System Parameters page - 1110
ibm-openbmc/webui-vue pull request #311
Opened 2024-11-26 07:15 UTC by vedangimittal

- Implemented System Parameters page - 1110
- Jira story: https://jsw.ibm.com/browse/PFEBMC-2390

2024-11-26 08:49 UTC, tiwari-nishant commented on src/store/modules/ResourceManagement/SystemParametersStore.js
> +      console.log('frequency', Number(frequency));
We can remove this log statement

2024-12-02 12:03 UTC, tiwari-nishant approved these changes

2024-12-02 17:28 UTC, Nikhil-Ashoka requested changes
I have seen issues with "Frequency cap" and "Runtime processor diagnostic policy". It is going back to the old value. Check with the same machine in vue2 code, Issue doesn't exist.

2024-12-02 17:40 UTC, Nikhil-Ashoka requested changes
Getting success when we have empty values in "RPD scheduled run time of day". It should throw error

2024-12-04 14:51 UTC, Nikhil-Ashoka approved these changes

2024-12-04 16:02 UTC, Nikhil-Ashoka approved these changes

2024-12-05 06:02 UTC, nabilpandiyalayil approved these changes

2024-12-05 14:26 UTC, merged