Implemented PCIe Topology page
ibm-openbmc/webui-vue pull request #312
Opened 2024-11-27 08:51 UTC by tiwari-nishant

* PCIe Topology Page Vue2 to Vue3
* Jira Story: https://jsw.ibm.com/browse/PFEBMC-2371

2024-12-03 12:47 UTC, Nikhil-Ashoka commented on src/views/HardwareStatus/PcieTopology/ResetLinkModal.vue
> +// import VuelidateMixin from '@/components/Mixins/VuelidateMixin';
Remove commented code

2024-12-03 12:50 UTC, Nikhil-Ashoka commented on src/views/HardwareStatus/PcieTopology/PcieTopology.vue
> +            {{ $t("pagePcieTopology.alert") }}
Why double quotes? I think the esLint is not working. Look into it.

2024-12-04 11:19 UTC, vedangimittal commented on src/store/modules/GlobalStore.js
> +      state.currentUser?.RoleId === 'OemIBMServiceAgent' || !state.currentUser,
state currentUser is neither initialised nor assigned a value anywhere in the file. getCurrentUser() and getAccountService() functions need to be included from older file. Or directly state userPrivilege can be used as well to get the role id of the user.

2024-12-05 07:52 UTC, nabilpandiyalayil requested changes

2024-12-05 07:52 UTC, nabilpandiyalayil commented on src/views/HardwareStatus/PcieTopology/PcieTopology.vue
> +  return globalStore.isServiceUser;
This is returning as true for all users(eg: admin)

2024-12-05 07:52 UTC, nabilpandiyalayil commented on src/views/HardwareStatus/PcieTopology/PcieTopology.vue
> +import { useI18n } from "vue-i18n";
use import i18n from '@/i18n';

2024-12-05 07:52 UTC, nabilpandiyalayil commented on src/views/HardwareStatus/PcieTopology/IdentifyLedsModal.vue
> +import { useI18n } from 'vue-i18n';
use import i18n from '@/i18n';

2024-12-05 07:52 UTC, nabilpandiyalayil commented on src/views/HardwareStatus/PcieTopology/ResetLinkModal.vue
> +import { useI18n } from 'vue-i18n';
use import i18n from '@/i18n';

2024-12-05 07:52 UTC, nabilpandiyalayil commented on src/views/HardwareStatus/PcieTopology/ResetLinkModal.vue
> +      emitUpdate('update:openResetModal',false)
Are we using these emits anywhere?

2024-12-05 07:52 UTC, nabilpandiyalayil commented on src/views/HardwareStatus/PcieTopology/ResetLinkModal.vue
> +  console.log("resetLink fn")
remove console logs

2024-12-06 05:13 UTC, tiwari-nishant commented on src/views/HardwareStatus/PcieTopology/ResetLinkModal.vue
> +      emitUpdate('update:openResetModal',false)
yes the root component PCIeToppology uses it to get the updated value

2024-12-06 12:35 UTC, nabilpandiyalayil approved these changes

2024-12-06 14:49 UTC, vedangimittal approved these changes

2024-12-06 16:40 UTC, merged